- hosts: all
  roles:
    - configure-swap
    - setup-stack-user
    - setup-tempest-user
    - setup-devstack-source-dirs
    - setup-devstack-log-dir
    - setup-devstack-cache
    - start-fresh-logging
    - write-devstack-local-conf
  # TODO(jeblair): remove when configure-mirrors is fixed  
  tasks:
    - name: Hack mirror_info
      shell:
        _raw_params: |
          mkdir /etc/ci
          cat << "EOF" > /etc/ci/mirror_info.sh
          export NODEPOOL_UCA_MIRROR=http://mirror.dfw.rax.openstack.org/ubuntu-cloud-archive
          EOF
      args:
        executable: /bin/bash
      become: true
